server:
  port: 8080
  servlet:
    context-path: /wuzhaojun

#名字为项目名
spring:
  application:
    name: wuzhaojun

    #邮箱配置
  mail:
    #默认发送邮件基于smtp协议 可不要
    protocol: smtp
    #smtp服务器地址
    host: smtp.qq.com
    #发送方的邮箱
    username: 2479138970@qq.com
    #发送方的密码（授权码或者QQ邮箱密码都可以）
    password: jquumilbgsdddhha
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true
  #            required: true

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  datasource:
    # 本机访问抓包的那台电脑的数据库
#        username: root
#        password: ''
#        url: jdbc:mysql://192.168.0.107:3306/invite_tenders?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8

    # 本机访问服务器的数据库
    username: EternalPain
    password: 'zjl.0115'
    url: jdbc:mysql://zbger.com:3306/wuzhaojun?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8

    # 服务器访问服务器的数据库
#    username: root
#   # password: 'dataset!163..'
#    password: ''
#    url: jdbc:mysql://192.168.0.102:3306/wuzhaojun?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8


    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙
      filters: stat,wall,log4j2
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        allow: 127.0.0.1
        login-username: dataset
        login-password: dataset
        #禁止那些ip
        #        deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true

#配置mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  #配置数据库表的实体类路径
  type-aliases-package: com.wuzhaojun.entity

#打印sql日志
logging:
  level:
    com.wuzhaojun.mapper: debug
